### ISSUE TITLE
Cat command is broken (again)

### ISSUE THREAD

**Issue by SolarDragon94** [ManyATrueNerd/matbot-issues#1]
**Your Discord Name:** Solar Dragon#7175

**This is a: (select one)**
- [x] Bug
- [ ] Feature Request 

**Please describe in detail the issue or the request:**
```
Using the cat command now returns an error, "An error occured while running that command.".

And, another note, "occurred" is misspelled.
```

**Comment by DerpyChap** [comment]
A fix has been pushed and the changes will be deployed shortly.
