### ISSUE TITLE
Bot fails to clean up after failed quote submit

### ISSUE THREAD

**Issue by ItsSharples** [ManyATrueNerd/matbot-issues#3]
**Your Discord Name:** Sharples#4444

**This is a: (select one)**
- [x] Bug
- [ ] Feature Request 

**Please describe in detail the issue or the request:**
```
Bot fails to clean up after failed quote submit request.
```

**Comment by DerpyChap** [comment]
The bot doesn't clean up any quote submissions, even valid ones. This allows the user to proofread what they sent (so they can see if they made a typo) or to let them resubmit a failed submission with any corrections needed.
